name: Release

on:
  workflow_run:
    workflows: ['Continuous Integration']
    branches: [ main ]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

      - name: Login to GitHub Packages Docker Registry
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Github Tag Bump
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        id: bump_version
        uses: anothrNick/github-tag-action@18284c78f6ac68868d5341f57c4f971fb5b7605c # 1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          WITH_V: true

      - run: echo "image=ghcr.io/deifyed/motoblog-pipeline" >> $GITHUB_ENV
      - run: echo "version=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Build Docker image
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: docker build --tag ${{ env.image }}:${{ env.version }} .

      - name: Push Docker image
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: docker push ${{ env.image }}:${{ env.version }}
